/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface;

/**
 *
 * @author JUANKA
 */
public class Inicio extends javax.swing.JFrame {

    /**
     * Creates new form Inicio
     */
    public Inicio() {
        initComponents();
        rsscalelabel.RSScaleLabel.setScaleLabel(background_Space,"src/images/start_background.png");
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu1 = new javax.swing.JPopupMenu();
        infrastructure_iconButton = new javax.swing.JLabel();
        start_iconButton = new javax.swing.JLabel();
        tecResources_iconButton = new javax.swing.JLabel();
        logOut_icon = new javax.swing.JLabel();
        jToggleButton1 = new javax.swing.JToggleButton();
        start_toggleButton = new javax.swing.JToggleButton();
        infrastructure_toggleButton = new javax.swing.JToggleButton();
        tecResources_toggleButton = new javax.swing.JToggleButton();
        historial_iconDel = new javax.swing.JLabel();
        error_iconDel = new javax.swing.JLabel();
        reservation_iconDel = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        service_text = new javax.swing.JLabel();
        welcome4_text = new javax.swing.JLabel();
        welcome3_text = new javax.swing.JLabel();
        welcome2_text = new javax.swing.JLabel();
        welcomeText = new javax.swing.JLabel();
        unispace_Text = new javax.swing.JLabel();
        whiteLogo = new javax.swing.JLabel();
        historial_buttonDel = new javax.swing.JLabel();
        report_buttonDel = new javax.swing.JLabel();
        myReserve_buttonDel = new javax.swing.JLabel();
        background_gradient = new javax.swing.JLabel();
        white_background = new javax.swing.JLabel();
        background_Space = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        infrastructure_iconButton.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        infrastructure_iconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/infrastructure_icon.png"))); // NOI18N
        getContentPane().add(infrastructure_iconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 439, 40, 30));

        start_iconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start_icon.png"))); // NOI18N
        getContentPane().add(start_iconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 240, 40, 30));

        tecResources_iconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/resources_icon.png"))); // NOI18N
        getContentPane().add(tecResources_iconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 340, 40, 30));

        logOut_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logOut_icon.png"))); // NOI18N
        getContentPane().add(logOut_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 640, 40, 30));

        jToggleButton1.setBackground(new java.awt.Color(44, 44, 44));
        jToggleButton1.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 20)); // NOI18N
        jToggleButton1.setForeground(new java.awt.Color(255, 255, 255));
        jToggleButton1.setText("Cerrar sesión");
        jToggleButton1.setBorder(null);
        jToggleButton1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton1.setIconTextGap(0);
        getContentPane().add(jToggleButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 250, 70));

        start_toggleButton.setBackground(new java.awt.Color(44, 44, 44));
        start_toggleButton.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 20)); // NOI18N
        start_toggleButton.setForeground(new java.awt.Color(255, 255, 255));
        start_toggleButton.setText("Inicio");
        start_toggleButton.setBorderPainted(false);
        start_toggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        start_toggleButton.setIconTextGap(0);
        getContentPane().add(start_toggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 70));

        infrastructure_toggleButton.setBackground(new java.awt.Color(44, 44, 44));
        infrastructure_toggleButton.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 20)); // NOI18N
        infrastructure_toggleButton.setForeground(new java.awt.Color(255, 255, 255));
        infrastructure_toggleButton.setText("Infraestructura");
        infrastructure_toggleButton.setBorder(null);
        infrastructure_toggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        infrastructure_toggleButton.setIconTextGap(0);
        getContentPane().add(infrastructure_toggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 250, 70));

        tecResources_toggleButton.setBackground(new java.awt.Color(44, 44, 44));
        tecResources_toggleButton.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 20)); // NOI18N
        tecResources_toggleButton.setForeground(new java.awt.Color(255, 255, 255));
        tecResources_toggleButton.setText("Tecnologicos");
        tecResources_toggleButton.setBorder(null);
        tecResources_toggleButton.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        tecResources_toggleButton.setIconTextGap(0);
        tecResources_toggleButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tecResources_toggleButtonActionPerformed(evt);
            }
        });
        getContentPane().add(tecResources_toggleButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 320, 250, 70));

        historial_iconDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/historial_icon.png"))); // NOI18N
        getContentPane().add(historial_iconDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 590, -1, -1));

        error_iconDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error_icon.png"))); // NOI18N
        getContentPane().add(error_iconDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, -1, -1));

        reservation_iconDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/booking_logo.png"))); // NOI18N
        getContentPane().add(reservation_iconDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, -1, -1));

        jLabel16.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 28)); // NOI18N
        jLabel16.setForeground(new java.awt.Color(255, 255, 255));
        jLabel16.setText("Historial");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, -1, -1));

        jLabel15.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 28)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Reportar error");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, -1, -1));

        jLabel14.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 28)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Mis reservas");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, -1, -1));

        service_text.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 56)); // NOI18N
        service_text.setForeground(new java.awt.Color(255, 255, 255));
        service_text.setText("Servicios");
        getContentPane().add(service_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, 60));

        welcome4_text.setFont(new java.awt.Font("Source Code Pro ExtraBold", 0, 25)); // NOI18N
        welcome4_text.setForeground(new java.awt.Color(255, 255, 255));
        welcome4_text.setText("recursos de la universidad");
        getContentPane().add(welcome4_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, 30));

        welcome3_text.setFont(new java.awt.Font("Source Code Pro ExtraBold", 0, 25)); // NOI18N
        welcome3_text.setForeground(new java.awt.Color(255, 255, 255));
        welcome3_text.setText("Un espacio para reservar y gestionar");
        getContentPane().add(welcome3_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        welcome2_text.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 54)); // NOI18N
        welcome2_text.setText("a UniSpace");
        getContentPane().add(welcome2_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        welcomeText.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 54)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 255, 255));
        welcomeText.setText("Bienvenido");
        getContentPane().add(welcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        unispace_Text.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 50)); // NOI18N
        unispace_Text.setForeground(new java.awt.Color(255, 255, 255));
        unispace_Text.setText("UniSpace");
        unispace_Text.setToolTipText("");
        getContentPane().add(unispace_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        whiteLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start_logo.png"))); // NOI18N
        getContentPane().add(whiteLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 107, 118));

        historial_buttonDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/historial_background.png"))); // NOI18N
        getContentPane().add(historial_buttonDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(925, 290, 334, 416));

        report_buttonDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error_background.png"))); // NOI18N
        getContentPane().add(report_buttonDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(589, 290, 336, 416));

        myReserve_buttonDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/booking_background.png"))); // NOI18N
        getContentPane().add(myReserve_buttonDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(252, 290, 336, 416));

        background_gradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_gradient.png"))); // NOI18N
        getContentPane().add(background_gradient, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 1010, 640));

        white_background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/whiteBackground_Gradient.png"))); // NOI18N
        getContentPane().add(white_background, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 1010, 640));

        background_Space.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_background.png"))); // NOI18N
        getContentPane().add(background_Space, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 0, 1290, 710));

        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(597, 286, 340, 420));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tecResources_toggleButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tecResources_toggleButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tecResources_toggleButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Inicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Inicio().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_Space;
    private javax.swing.JLabel background_gradient;
    private javax.swing.JLabel error_iconDel;
    private javax.swing.JLabel historial_buttonDel;
    private javax.swing.JLabel historial_iconDel;
    private javax.swing.JLabel infrastructure_iconButton;
    private javax.swing.JToggleButton infrastructure_toggleButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JLabel logOut_icon;
    private javax.swing.JLabel myReserve_buttonDel;
    private javax.swing.JLabel report_buttonDel;
    private javax.swing.JLabel reservation_iconDel;
    private javax.swing.JLabel service_text;
    private javax.swing.JLabel start_iconButton;
    private javax.swing.JToggleButton start_toggleButton;
    private javax.swing.JLabel tecResources_iconButton;
    private javax.swing.JToggleButton tecResources_toggleButton;
    private javax.swing.JLabel unispace_Text;
    private javax.swing.JLabel welcome2_text;
    private javax.swing.JLabel welcome3_text;
    private javax.swing.JLabel welcome4_text;
    private javax.swing.JLabel welcomeText;
    private javax.swing.JLabel whiteLogo;
    private javax.swing.JLabel white_background;
    // End of variables declaration//GEN-END:variables
}
