/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Interface_employed;

import Interface.Historial;
import Interface.Insfractuture_resources;
import Interface.Login;
import Interface.Reportar_error;
import Interface.booking_page;
import Interface.tecno_resources;

/**
 *
 * @author PC{
 */
public class inicio_empleado extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(inicio_empleado.class.getName());

    /**
     * Creates new form NewJFrame
     */
    public inicio_empleado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        whiteLogo = new javax.swing.JLabel();
        unispace_Text = new javax.swing.JLabel();
        welcomeText = new javax.swing.JLabel();
        welcome2_text = new javax.swing.JLabel();
        welcome4_text = new javax.swing.JLabel();
        welcome3_text = new javax.swing.JLabel();
        start_iconButton = new javax.swing.JLabel();
        start_button = new javax.swing.JButton();
        service_text = new javax.swing.JLabel();
        logOutButton = new javax.swing.JButton();
        logOut_icon = new javax.swing.JLabel();
        reservation_iconDel = new javax.swing.JLabel();
        booking_text = new javax.swing.JLabel();
        booking_button = new javax.swing.JButton();
        error_iconDel = new javax.swing.JLabel();
        error_text = new javax.swing.JLabel();
        error_button = new javax.swing.JButton();
        historial_iconDel = new javax.swing.JLabel();
        historial_text = new javax.swing.JLabel();
        historial_button = new javax.swing.JButton();
        background_gradient = new javax.swing.JLabel();
        background_Space = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        whiteLogo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start_logo.png"))); // NOI18N
        getContentPane().add(whiteLogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 10, 107, 118));

        unispace_Text.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 50)); // NOI18N
        unispace_Text.setForeground(new java.awt.Color(255, 255, 255));
        unispace_Text.setText("UniSpace");
        unispace_Text.setToolTipText("");
        getContentPane().add(unispace_Text, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 10, -1, -1));

        welcomeText.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 54)); // NOI18N
        welcomeText.setForeground(new java.awt.Color(255, 255, 255));
        welcomeText.setText("Bienvenido");
        getContentPane().add(welcomeText, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 90, -1, -1));

        welcome2_text.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 54)); // NOI18N
        welcome2_text.setText("a UniSpace");
        getContentPane().add(welcome2_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 90, -1, -1));

        welcome4_text.setFont(new java.awt.Font("Source Code Pro ExtraBold", 0, 25)); // NOI18N
        welcome4_text.setForeground(new java.awt.Color(255, 255, 255));
        welcome4_text.setText("y analizar el uso de los recursos de la universidad");
        getContentPane().add(welcome4_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, -1, 30));

        welcome3_text.setFont(new java.awt.Font("Source Code Pro ExtraBold", 0, 25)); // NOI18N
        welcome3_text.setForeground(new java.awt.Color(255, 255, 255));
        welcome3_text.setText("Un espacio deonde puedes supervisar, gestionar");
        getContentPane().add(welcome3_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 160, -1, -1));

        start_iconButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/start_icon.png"))); // NOI18N
        getContentPane().add(start_iconButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 240, 40, 30));

        start_button.setBackground(new java.awt.Color(44, 44, 44));
        start_button.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 20)); // NOI18N
        start_button.setForeground(new java.awt.Color(255, 255, 255));
        start_button.setText("Inicio");
        start_button.setBorder(null);
        start_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                start_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(start_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 220, 250, 70));

        service_text.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 56)); // NOI18N
        service_text.setForeground(new java.awt.Color(255, 255, 255));
        service_text.setText("Servicios");
        getContentPane().add(service_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 250, -1, 60));

        logOutButton.setBackground(new java.awt.Color(44, 44, 44));
        logOutButton.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 20)); // NOI18N
        logOutButton.setForeground(new java.awt.Color(255, 255, 255));
        logOutButton.setText("Cerrar Sesion ");
        logOutButton.setBorder(null);
        logOutButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logOutButtonMouseClicked(evt);
            }
        });
        logOutButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logOutButtonActionPerformed(evt);
            }
        });
        getContentPane().add(logOutButton, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 620, 250, 70));

        logOut_icon.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/logOut_icon.png"))); // NOI18N
        getContentPane().add(logOut_icon, new org.netbeans.lib.awtextra.AbsoluteConstraints(17, 640, 40, 30));

        reservation_iconDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/booking_logo.png"))); // NOI18N
        getContentPane().add(reservation_iconDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 590, -1, -1));

        booking_text.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 28)); // NOI18N
        booking_text.setForeground(new java.awt.Color(255, 255, 255));
        booking_text.setText("Gestión de reservas");
        getContentPane().add(booking_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 640, -1, -1));

        booking_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/booking_background.png"))); // NOI18N
        booking_button.setBorder(null);
        booking_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                booking_buttonMouseClicked(evt);
            }
        });
        booking_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                booking_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(booking_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 290, 336, 410));

        error_iconDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error_icon.png"))); // NOI18N
        getContentPane().add(error_iconDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 590, -1, -1));

        error_text.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 28)); // NOI18N
        error_text.setForeground(new java.awt.Color(255, 255, 255));
        error_text.setText("Reportes");
        getContentPane().add(error_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 640, -1, -1));

        error_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/error_background.png"))); // NOI18N
        error_button.setBorder(null);
        error_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                error_buttonMouseClicked(evt);
            }
        });
        error_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                error_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(error_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 290, 336, 410));

        historial_iconDel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/historial_icon.png"))); // NOI18N
        getContentPane().add(historial_iconDel, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 590, -1, -1));

        historial_text.setFont(new java.awt.Font("League Spartan ExtraBold", 0, 28)); // NOI18N
        historial_text.setForeground(new java.awt.Color(255, 255, 255));
        historial_text.setText("Estadísticas");
        getContentPane().add(historial_text, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, -1, -1));

        historial_button.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/historial_background.png"))); // NOI18N
        historial_button.setBorder(null);
        historial_button.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                historial_buttonMouseClicked(evt);
            }
        });
        historial_button.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                historial_buttonActionPerformed(evt);
            }
        });
        getContentPane().add(historial_button, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 290, 330, 410));

        background_gradient.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/background_gradient.png"))); // NOI18N
        getContentPane().add(background_gradient, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 70, 1010, 640));

        background_Space.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/black_background.png"))); // NOI18N
        getContentPane().add(background_Space, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1280, 710));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void start_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_start_buttonActionPerformed
        // Nada por el momento
    }//GEN-LAST:event_start_buttonActionPerformed

    private void logOutButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logOutButtonMouseClicked
        this.dispose();                     // Cierra la ventana actual (Inicio)
        Login login = new Login(); // Crea la nueva ventana(Login)
        login.setVisible(true);        // La muestra
    }//GEN-LAST:event_logOutButtonMouseClicked

    private void logOutButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logOutButtonActionPerformed

    }//GEN-LAST:event_logOutButtonActionPerformed

    private void booking_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_booking_buttonMouseClicked
        this.dispose();                     // Cierra la ventana actual (Login)
        booking_page booking = new booking_page(); // Crea la nueva ventana
        booking.setVisible(true);        // La muestra
    }//GEN-LAST:event_booking_buttonMouseClicked

    private void booking_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_booking_buttonActionPerformed

    }//GEN-LAST:event_booking_buttonActionPerformed

    private void error_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_error_buttonMouseClicked
        this.dispose();                     // Cierra la ventana actual (Inicio)
        Reportar_error error_page= new Reportar_error(); // Crea la nueva ventana(Error)
        error_page.setVisible(true);
    }//GEN-LAST:event_error_buttonMouseClicked

    private void error_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_error_buttonActionPerformed

    }//GEN-LAST:event_error_buttonActionPerformed

    private void historial_buttonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_historial_buttonMouseClicked
        this.dispose();                     // Cierra la ventana actual (Inicio)
        Historial histo= new Historial(); // Crea la nueva ventana(Historial)
        histo.setVisible(true);
    }//GEN-LAST:event_historial_buttonMouseClicked

    private void historial_buttonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_historial_buttonActionPerformed

    }//GEN-LAST:event_historial_buttonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new inicio_empleado().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel background_Space;
    private javax.swing.JLabel background_gradient;
    private javax.swing.JButton booking_button;
    private javax.swing.JLabel booking_text;
    private javax.swing.JButton error_button;
    private javax.swing.JLabel error_iconDel;
    private javax.swing.JLabel error_text;
    private javax.swing.JButton historial_button;
    private javax.swing.JLabel historial_iconDel;
    private javax.swing.JLabel historial_text;
    private javax.swing.JButton logOutButton;
    private javax.swing.JLabel logOut_icon;
    private javax.swing.JLabel reservation_iconDel;
    private javax.swing.JLabel service_text;
    private javax.swing.JButton start_button;
    private javax.swing.JLabel start_iconButton;
    private javax.swing.JLabel unispace_Text;
    private javax.swing.JLabel welcome2_text;
    private javax.swing.JLabel welcome3_text;
    private javax.swing.JLabel welcome4_text;
    private javax.swing.JLabel welcomeText;
    private javax.swing.JLabel whiteLogo;
    // End of variables declaration//GEN-END:variables
}
